Drakkar-Software/OctoBot-Tentacles-Manager

octobot_tentacles_manager/managers/tentacle_manager.py, octobot_tentacles_manager/util/tentacle_explorer.py, tests/api/test_configurator.py, tests/api/test_installer.py
https://www.python.org/dev/peps/pep-0471/
=> use scandir instead of listdir for better performances

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, requirements.txt
- Dev mode
- Import issues
- Logger issues
- Websocket tentacle type
=> [Version] v2.0.1

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, requirements.txt
=> [Version] v2.1.5

octobot_tentacles_manager/creators/tentacles_package_creator.py, setup.cfg, tests/api/test_creator.py
issue: exporting into a git repo is deleting the git files 😂
=> do not cleanup when exporting into a directory

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, requirements.txt
=> [Version] v2.2.3

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/cli.py, setup.py
=> add entrypoint

octobot_tentacles_manager/api/configurator.py, octobot_tentacles_manager/configuration/config_file.py, octobot_tentacles_manager/configuration/tentacle_configuration.py, octobot_tentacles_manager/configuration/tentacles_setup_configuration.py, octobot_tentacles_manager/constants.py, octobot_tentacles_manager/managers/tentacle_manager.py, octobot_tentacles_manager/managers/tentacles_setup_manager.py, requirements.txt, tests/__init__.py, tests/api/test_installer.py, tests/configuration/test_tentacle_configuration.py, tests/managers/test_tentacles_setup_manager.py, tests/workers/test_install_worker.py, tests/workers/test_uninstall_worker.py, tests/workers/test_update_worker.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/145
=> enable profiles

.github/workflows/main.yml, octobot_tentacles_manager/api/__init__.py, octobot_tentacles_manager/api/creator.py, octobot_tentacles_manager/api/uploader.py, octobot_tentacles_manager/cli.py, octobot_tentacles_manager/exporters/tentacle_bundle_exporter.py, octobot_tentacles_manager/uploaders/__init__.py, octobot_tentacles_manager/uploaders/nexus_uploader.py, octobot_tentacles_manager/uploaders/uploader.py, tests/uploaders/__init__.py, tests/uploaders/test_nexus_uploader.py
=> [Uploader] Add nexus uploader

octobot_tentacles_manager/api/creator.py, octobot_tentacles_manager/cli.py
=> [CLI] Add upload created package

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/constants.py, octobot_tentacles_manager/exporters/artifact_exporter.py, octobot_tentacles_manager/exporters/tentacle_package_exporter.py, octobot_tentacles_manager/models/tentacle_package.py, tests/api/test_creator.py
=> [Exporters] Fix previous folder export from package_name #93 

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/constants.py, requirements.txt, tests/api/test_installer.py, tests/workers/test_install_worker.py
=> [Version] v2.4.6

octobot_tentacles_manager/configuration/tentacle_configuration.py, octobot_tentacles_manager/configuration/tentacles_setup_configuration.py, octobot_tentacles_manager/managers/tentacle_manager.py, octobot_tentacles_manager/workers/repair_worker.py, tests/api/test_installer.py, tests/workers/test_install_worker.py, tests/workers/test_uninstall_worker.py, tests/workers/test_update_worker.py
Depends on https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/118
=> [TentacleManager] Remove import tentacle config if any

octobot_tentacles_manager/configuration/tentacles_setup_configuration.py, tests/api/test_installer.py, tests/configuration/test_tentacles_setup_configuration.py
Depends on https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/121
=> [TentacleSetupConfiguration] Fix tentacle not in config activation filter

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/api/__init__.py, octobot_tentacles_manager/api/loader.py, octobot_tentacles_manager/configuration/tentacles_setup_configuration.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/271
=> [Profiles] do not update installation_context on imported profiles

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/exporters/artifact_exporter.py
=> Fix metadata

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/loaders/tentacle_loading.py, octobot_tentacles_manager/managers/profiles_manager.py, octobot_tentacles_manager/workers/install_worker.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/303
=> backtester

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/configuration/tentacles_setup_configuration.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/309
=> fix config activation in setup config fixer

octobot_tentacles_manager/util/hashing.py
I'm using scripted trading mode as a base for many things, but I'm not using the TRADING_SCRIPT_MODULE. 
with this change it will work with or without  a TRADING_SCRIPT_MODULE
=> [Scripted] allow hashing for scripted mode without script

CHANGELOG.md, README.md, octobot_tentacles_manager/__init__.py, octobot_tentacles_manager/configuration/config_file.py
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/396
=> Config save

requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/419
=> [Requirements] bump commons
